# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-api-configmap
  namespace: default
data:
  API_PORT: "8080"
  API_DB_FILEPATH: /var/lib/synergychat/api/db.json
---

